apiVersion: apps/v1
kind: Deployment
metadata:
  name: tilt-local-metrics-collector
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: tilt-local-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
      app.kubernetes.io/part-of: tilt-local-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
        app.kubernetes.io/part-of: tilt-local-metrics
    spec:
      volumes:
        - name: config-vol
          configMap:
            name: tilt-otel-collector-config
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
                
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:0.14.0
          command:
          - "/otelcol"
          - "--config=/conf/otel-collector-config.yaml"
          
          ports:
            - name: pprof
              containerPort: 1777 
              protocol: TCP
            - name: zpages
              containerPort: 55679 
              protocol: TCP
            - name: receiver
              containerPort: 55678
              protocol: TCP
            - name: prom-exporter
              containerPort: 55681
              protocol: TCP
            - name: healthcheck
              containerPort: 13133
              protocol: TCP
          volumeMounts:
            - name: config-vol
              mountPath: /conf
          
          readinessProbe:
            httpGet:
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tilt-local-metrics-collector
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: tilt-local-metrics
spec:
  ports:
  - name: receiver
    port: 55678
    protocol: TCP
    targetPort: 55678
  - name: exporter
    port: 55681
    protocol: TCP
    targetPort: 55681
  selector:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: tilt-local-metrics
