apiVersion: v1
kind: ConfigMap
metadata:
  name: tilt-prometheus-config
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: tilt-local-metrics
data:
  prometheus-config: |
    global:
      scrape_interval: 15s

    scrape_configs:
    - job_name: 'otel-collector'
      scrape_interval: 5s
      static_configs:
        - targets: ['tilt-local-metrics-collector:55681']
